name: Python Lint
description: GitHub Action that lints a Python-based repository.
inputs:
  python-version:
    description: Python version to install on the GitHub runner.
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Poetry
      if: hashFiles('pyproject.toml') != ''
      shell: bash
      run: |
        if ! command -v poetry &> /dev/null; then
          pipx install poetry
        fi

    - name: Install pip dependencies
      if: hashFiles('pyproject.toml') == ''
      shell: bash
      run: |
        pip install -e .

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0
